### ISSUE TITLE
A simple message when trying to recognize songs without internet

### ISSUE THREAD

**Issue by CharDSonDev** [SeaDve/Mousai#38]
When trying to recognize a song without an internet connection, the program displays the complete exception and does not display easy-to-recognize information that is happening. If you do not realize if your Internet is not working well or you are disconnected, this can make you feel that the program is not working properly.

![Screenshot from 2021-11-16 16-58-06](https://user-images.githubusercontent.com/36754778/142069618-7871fd7b-1049-46cc-8026-dccecdf7c46b.png)

**Comment by SeaDve** [comment]
Why was it closed?

**Comment by CharDSonDev** [comment]
> Why was it closed?

It got no attention and I thought it wasn't important

**Comment by SeaDve** [comment]
Of course, it is important. It is just I also have school plus work, and other projects. I'll look back at the issue when I have time. I also have a lot of planned works for Mousai, and the bug tracker is great way to keep track of those

**Comment by SeaDve** [comment]
Currently working on getting this fixed

**Comment by SeaDve** [comment]
This is fixed now in the `rust` branch

**Comment by SeaDve** [comment]
Closing since the fix is now at main branch

**Comment by chardinson** [comment]
I still continue to be embarrassed by my previous message, an apology for that attitude.

**Comment by SeaDve** [comment]
No worries, don't think about it
